### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by 1226689046** [gcpaas/DataRoom#14]
在GroovyUtils.buildClassSafe()方法内，有以下代码：
```java
new NoSystemExitSandbox().register();
new NoRunTimeSandbox().register();
new NoFileSandbox().register();
```
其中register方法如下：
```
threadInterceptors.get().add(this);
```
这种情况，在线程复用比较多的情况下，会造成threadInterceptors内容越来越多，时间长会产生StockOverflowError

![微信图片_20240426090324](https://github.com/gcpaas/DataRoom/assets/26176405/4f9e3b28-47c0-489a-8fe4-5ca88000076f)

**Comment by jian-man-man** [comment]
已修复 详见 https://github.com/gcpaas/dataset/commit/9fd8e18f187074b9d5cae71eac2f7cda6ad9bc30
