### ISSUE TITLE
图标的指标不是从小到大的，而是从大

### ISSUE THREAD

**Issue by dongcheng8918** [gcpaas/DataRoom#9]
<img width="629" alt="微信图片_20231108142805" src="https://github.com/gcpaas/DataRoom/assets/52097801/1c72a713-65c3-4855-8704-d7806af7e2de">

**Comment by shi-qing-huan** [comment]
这种情况多半是y轴绑定的数据的格式非数字类型，图表组件在处理非数字类型的值时，无法自动排序，可参考如下解决方案
1：修改数据集中数据格式为数字类型
2：使用数据处理脚本进行强制类型转换，如 data.forEach(item => {
  item.xxx= Number(item.xxx)
})
